name : PRECISION-Panc
brand : PRECISION-Panc
description : Precision medicine for pancreatic cancer
keyword : pancreatic cancer
url : http://www.precisionpanc.org
email : Derek.Wright@glasgow.ac.uk
twitter : precisionpanc
github : wrightdw   
author : Derek Wright, Daigo Fujiwara
analytics : UA-59581444-1
year : 2015
markdown : kramdown
collections:
  - our_history
  
